---
kind: Template
apiVersion: v1

objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: epp-test
  spec:
    type: NodePort
    {% if PORT %}
    ports:
    - port: {{ PORT }}
    {% endif %}
    selector:
      name: epp-test
      test: {{ BARE_ENV }}
