---
kind: Template
apiVersion: v1

objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: expenv-test
    app: "$METADATA_APP"
    component: "${METADATA_COMPONENT}"
  spec:
    type: NodePort
    ports:
    - port: $PORT
    selector:
      name: expenv-test
      test: "$BARE_ENV"
